#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ast
import json
import re
from pathlib import Path


EXACT_TRANSLATIONS: dict[str, str] = {
    "Account": "Conta",
    "Accounts": "Contas",
    "Account Name": "Nome da conta",
    "Account Status": "Status da conta",
    "Active": "Ativo",
    "ActiveSync": "ActiveSync",
    "Add": "Adicionar",
    "Add Account": "Adicionar conta",
    "Add Domain": "Adicionar domínio",
    "Address": "Endereço",
    "Admin": "Administrador",
    "Admin Console": "Console de administração",
    "Advanced": "Avançado",
    "Aliases": "Aliases",
    "All": "Todos",
    "Allow": "Permitir",
    "Apply": "Aplicar",
    "Are you sure?": "Tem certeza?",
    "Authentication": "Autenticação",
    "Authorized Senders": "Remetentes autorizados",
    "Backup": "Backup",
    "Backups": "Backups",
    "Bucket": "Bucket",
    "Buckets": "Buckets",
    "Cancel": "Cancelar",
    "Certificate": "Certificado",
    "Certificates": "Certificados",
    "Change Password": "Alterar senha",
    "Close": "Fechar",
    "Confirm": "Confirmar",
    "Contacts": "Contatos",
    "COS": "COS",
    "Create": "Criar",
    "Create Account Wizard": "Assistente de criação de conta",
    "Create New COS": "Criar novo COS",
    "CREATE WITH THESE DATA": "CRIAR COM ESTES DADOS",
    "Created": "Criado",
    "Dashboard": "Painel",
    "Default": "Padrão",
    "Default COS": "COS padrão",
    "Delete": "Excluir",
    "Delegated Admin": "Administrador delegado",
    "Description": "Descrição",
    "Details": "Detalhes",
    "Disable": "Desativar",
    "Disabled": "Desativado",
    "Display Name": "Nome de exibição",
    "Display Name (Auto-fill)": "Nome de exibição (preenchimento automático)",
    "Domain": "Domínio",
    "Domain Admin": "Administrador do domínio",
    "Domain Name": "Nome do domínio",
    "Domains": "Domínios",
    "Done": "Concluído",
    "Edit": "Editar",
    "Email": "E-mail",
    "Enable": "Ativar",
    "Enabled": "Ativado",
    "Error": "Erro",
    "Errors": "Erros",
    "Filter": "Filtro",
    "General": "Geral",
    "General Settings": "Configurações gerais",
    "Group": "Grupo",
    "Groups": "Grupos",
    "Help Desk Admin": "Administrador de suporte",
    "Hide": "Ocultar",
    "Host": "Host",
    "Hostname": "Nome do host",
    "Language": "Idioma",
    "List": "Lista",
    "Loading": "Carregando",
    "Login": "Login",
    "Logout": "Sair",
    "Mail": "E-mail",
    "Mailbox": "Caixa postal",
    "Mailing List": "Lista de distribuição",
    "Mailing Lists": "Listas de distribuição",
    "Manage": "Gerenciar",
    "Management": "Gerenciamento",
    "Middle Name Initials": "Iniciais do nome do meio",
    "MTA": "MTA",
    "Name": "Nome",
    "New": "Novo",
    "Next": "Próximo",
    "No": "Não",
    "Notifications": "Notificações",
    "OK": "OK",
    "Operations": "Operações",
    "Password": "Senha",
    "Password*": "Senha*",
    "Pending": "Pendente",
    "Permission": "Permissão",
    "Permissions": "Permissões",
    "Preferences": "Preferências",
    "Privacy": "Privacidade",
    "Queued": "Na fila",
    "Quota": "Cota",
    "Remove": "Remover",
    "Repeat Password": "Repetir senha",
    "Repeat Password*": "Repetir senha*",
    "Reset": "Redefinir",
    "Resources": "Recursos",
    "Restore": "Restaurar",
    "Retry": "Tentar novamente",
    "Running": "Em execução",
    "Save": "Salvar",
    "Search": "Pesquisar",
    "Server": "Servidor",
    "Servers": "Servidores",
    "Service": "Serviço",
    "Services": "Serviços",
    "Settings": "Configurações",
    "Show": "Exibir",
    "Status": "Status",
    "Storage": "Armazenamento",
    "Surname": "Sobrenome",
    "Time Zone": "Fuso horário",
    "Type": "Tipo",
    "Update": "Atualizar",
    "User": "Usuário",
    "User Management Admin": "Administrador de usuários",
    "User will change password on next login": "O usuário alterará a senha no próximo login",
    "Users": "Usuários",
    "View": "Visualizar",
    "Volume": "Volume",
    "Volumes": "Volumes",
    "Warning": "Aviso",
    "Yes": "Sim",
    "Sunday": "Domingo",
    "Monday": "Segunda-feira",
    "Tuesday": "Terça-feira",
    "Wednesday": "Quarta-feira",
    "Thursday": "Quinta-feira",
    "Friday": "Sexta-feira",
    "Saturday": "Sábado",
    "Days": "Dias",
    "Hours": "Horas",
    "Minutes": "Minutos",
    "Sec": "Seg",
    "Public": "Público",
    "Private": "Privado",
    "Work Week": "Semana útil",
    "60 Minutes": "60 minutos",
    "10 minute time limit": "Limite de 10 minutos",
    "Changes have been saved successfully": "Alterações salvas com sucesso",
    "Something went wrong": "Algo deu errado",
    "There are no items to show": "Não há itens para exibir",
    "No results found": "Nenhum resultado encontrado",
    "Search results": "Resultados da pesquisa",
}


KEY_TRANSLATIONS: dict[str, str] = {
    "accountDetails.auto_fill_user_is_disabled": "Preenchimento automático do usuário desativado",
    "accountDetails.default_COS": "COS padrão",
    "accountDetails.user_will_change_password_on_next_login": "O usuário alterará a senha no próximo login",
    "account.new.create_account_wizard": "Assistente de criação de conta",
    "account.new.create_otp_wizard": "Assistente de criação de OTP",
    "account_details.ADD": "ADICIONAR",
    "account_details.DELETE": "EXCLUIR",
    "account_details.NEXT": "PRÓXIMO",
    "account_details.a_user": "Um usuário",
    "account_details.able_to_see_password_once": "Atenção: você poderá ver a senha <bold>apenas uma vez.</bold>",
    "account_details.abq_status": "Status ABQ",
    "account_details.account_with_read_only_rights": "Contas com permissão <bold>somente leitura</bold>",
    "account_details.account_with_read_write_rights": "Contas com permissão <bold>leitura/gravação</bold>",
    "account_details.account_with_send_rights": "Conta com permissões <bold>Enviar como/Enviar em nome de</bold>",
    "account_details.add_forwarded_invites_to_calendar": "Adicionar automaticamente compromissos encaminhados ao calendário",
    "account_details.add_the_account_group_with_selected_rights": "ADICIONAR A CONTA/GRUPO COM AS PERMISSÕES SELECIONADAS",
    "account_details.add_user_on_delegates_list": "Adicionar usuário à lista de delegados",
    "account_details.allow_sending_cancellation_mail": "Permitir envio de e-mail de cancelamento",
    "account_details.an_existing_group": "Um grupo existente",
    "account_details.appointments_default_duration": "Duração padrão dos compromissos",
    "account_details.as": "como",
    "account_details.as_new_email_arrives": "Quando um novo e-mail chegar",
    "account_details.auto_delete_duplicate_messages": "Excluir automaticamente mensagens duplicadas",
    "account_details.click_on_the_pencil_to_edit": "Clique no lápis para editar o alias disponível ou no X para excluí-lo",
    "account_details.click_to_revert": "Clique para reverter.",
    "account_details.create": "CRIAR",
    "account_details.default_COS": "COS padrão",
    "account_details.default_view.day": "Visualização diária",
    "account_details.default_view.list": "Visualização em lista",
    "account_details.default_view.month": "Visualização mensal",
    "account_details.default_view.week": "Visualização semanal",
    "account_details.default_view.work_week": "Visualização de semana útil",
    "account_details.delegate_created_successfully": "Permissões de delegado criadas com sucesso",
    "account_details.delegate_deleted_successfully": "Permissões de delegado excluídas com sucesso",
    "account_details.delegate_rights": "Permissões do delegado",
    "account_details.delegate_updated_successfully": "Permissões de delegado atualizadas com sucesso",
    "account_details.delegated_administration": "Administração delegada",
    "account_details.delete_password": "Excluir senha",
    "account_details.delete_password_of_user_ldap": "Você está excluindo a senha de <bold>{{name}}</bold> do LDAP. Tem certeza de que deseja excluí-la?",
    "account_details.delete_user_password": "EXCLUIR SENHA DO USUÁRIO NO LDAP",
    "account_details.deligate_abstract_text": "O usuário {{granteeEmail}} poderá enviar e-mails {{right}} {{targetEmail}}",
    "account_details.enable_past_due_reminders": "Ativar lembretes de compromissos no passado",
    "account_details.forwarding_addresses_hidden_from_the_user": "Endereços de encaminhamento ocultos do usuário",
    "account_details.forwarding_addresses_specified_by_the_user": "Endereços de encaminhamento especificados pelo usuário",
    "account_details.forwarding_calendar_invitations_to_these_addresses": "Encaminhar convites de calendário para estes endereços",
    "account_details.global_administration": "Administração global",
    "account_details.hidden_in_gal": "Oculto na GAL",
    "account_details.i_have_copied_the_password": "COPIEI A SENHA",
    "account_details.included_in_backup": "Incluído no backup",
    "account_details.inherited_value_was": "O valor herdado era: {{value}}",
    "account_details.label": "Rótulo",
    "account_details.mail_signature": "Assinatura de e-mail",
    "account_details.manage_aliases": "GERENCIAR ALIASES",
    "account_details.manage_no_rights_to_send_mails": "Gerenciar (sem permissão para enviar e-mails)",
    "account_details.manage_the_aliases_for_this_account": "Gerenciar aliases desta conta",
    "account_details.manuallly": "Manualmente",
    "account_details.new_alias_name": "Novo nome de alias",
    "account_details.on_behalf_of": "em nome de",
    "account_details.otp_devices": "Dispositivos OTP",
    "account_details.passphrasaId": "ID da frase secreta",
    "account_details.read_mails_only": "Ler e-mails apenas (sem permissão para enviar e-mails)",
    "account_details.read_only": "Somente leitura",
    "account_details.read_write": "Leitura/gravação",
    "account_details.remove": "REMOVER",
    "account_details.remove_all": "REMOVER TODOS",
    "account_details.right_for_selected_user_deleted_successfully": "Permissão do usuário selecionado excluída com sucesso",
    "account_details.save_to_sent": "Salvar em enviados",
    "account_details.search_here_for_an_account": "Pesquise uma conta aqui",
    "account_details.secret_code": "Código secreto",
    "account_details.select_mode": "SELECIONAR MODO",
    "account_details.send": "ENVIAR",
    "account_details.send_check": "Enviar",
    "account_details.send_mails_only": "Enviar e-mails apenas (sem permissão para ler pastas)",
    "account_details.send_on_behalf_of_check": "Enviar em nome de",
    "account_details.send_read_manage_mails": "Enviar, ler e gerenciar e-mails (todas as opções acima)",
    "account_details.send_read_mails": "Enviar e ler e-mails (sem permissão para criar pastas ou gerenciar e-mails)",
    "account_details.send_recipients_see_the_mail": "Enviar {{right}} (os destinatários verão este remetente {{targetEmail}})",
    "account_details.send_the_otp_to": "Enviar OTP para",
    "account_details.sendin_options": "Opções de envio",
    "account_details.service_label_password": "Senha de {{ service_label }}",
    "account_details.service_password": "Senha de serviço",
    "account_details.services": "Serviços",
    "account_details.services_passphrase": "Frase secreta de serviços",
    "account_details.services_passphrase_created_successfully": "Frase secreta de serviços criada com sucesso",
    "account_details.services_passphrase_deleted_successfully": "Frase secreta de serviços excluída com sucesso",
    "account_details.set_rights": "DEFINIR PERMISSÕES",
    "account_details.start_typing_account": "Comece a digitar uma conta/grupo para adicionar permissões",
    "account_details.switch_advanced": "Alternar para visualização avançada",
    "account_details.switch_simplified": "Alternar para visualização simplificada",
    "account_details.this_account_is_a_direct_member_of": "Esta conta é membro direto de",
    "account_details.this_account_is_a_in_direct_member_of": "Esta conta é membro indireto de",
    "account_details.this_user_must_change_password": "Este usuário deve alterar a senha",
    "account_details.type_the_new_alias_name": "Digite o novo alias e selecione um domínio para adicioná-lo aos aliases disponíveis",
    "account_details.unlimited": "Ilimitado",
    "account_details.use_gal_to_auto_fill": "Usar GAL para preenchimento automático",
    "account_details.use_ical_delegation_model_for_shared_calendars": "Usar modelo de delegação iCal para calendários compartilhados",
    "account_details.user_can_specify_forwarding_address": "Usuário pode especificar endereço de encaminhamento",
    "account_details.user_can_specify_mail_forwarding_filter": "Usuário pode especificar filtro de encaminhamento de e-mail",
    "account_details.user_password_deleted": "Senha do usuário excluída com sucesso",
    "account_details.user_password_set": "Senha do usuário definida com sucesso",
    "account_details.view_mail_as_html": "Visualizar e-mail como HTML",
    "account_details.what_rights_will_the_delegate_have": "Quais permissões o delegado terá?",
    "account_details.who_will_be_delegates": "Quem serão os delegados?",
    "account_details.your_available_aliases": "Seus aliases disponíveis",
    "commons.create_with_there_data": "CRIAR COM ESTES DADOS",
    "dashboard.core_version": "Versão Core",
    "dashboard.go_to_mailstores_server_list": "Ir para lista de servidores mailstore",
    "dashboard.quick_access_to": "Acesso rápido a",
    "dashboard.server_name": "Nome do servidor",
    "domain.type_the exact_domain_name": "Digite o nome exato do domínio",
    "domain.mailbox_quota": "Cota de caixa postal",
    "label.class_of_service": "Classe de serviço",
    "label.class_of_service_cos": "Classe de serviço (COS)",
    "label.default_class_of_service": "Classe de serviço padrão",
    "label.distribution_list": "Lista de distribuição",
    "label.distribution_lists": "Listas de distribuição",
    "label.domain_primarybar_tooltip": "Visualize os <bold>detalhes dos domínios</bold> e <bold>gerencie</bold> recursos como <bold>contas, listas de distribuição, recursos</bold> e <bold>mais</bold>.",
    "label.global_address_list": "Lista global de endereços",
    "label.home": "Residencial",
    "label.items_per_page": "itens por página",
    "label.last_access": "Último acesso",
    "label.mailbox_quota": "Cota de caixa postal",
    "label.mailstores_list": "Lista de mailstores",
    "label.new_distribution_list": "Nova lista de distribuição",
    "label.of": "de",
    "label.quarantine": "Quarentena",
    "label.server_name": "Nome do servidor",
    "label.showing": "Exibindo",
    "label.virtual_hosts": "Hosts virtuais",
    "label.virtual_hosts_and_certificates": "Hosts virtuais e certificado",
    "mta.server_name": "Nome do servidor",
    "quarantine.quarantine": "Quarentena",
    "welcome": "Bem-vindo",
    "label.account_status": "Status da conta",
    "label.advance_edit_display_name": "Nome de exibição",
    "label.administration": "ADMINISTRAÇÃO",
    "label.administrators": "Administradores",
    "label.city": "Cidade",
    "label.company": "Empresa",
    "label.configuration": "CONFIGURAÇÃO",
    "label.country": "País",
    "label.default_cos": "COS padrão",
    "label.description": "Descrição",
    "label.display_name": "Nome de exibição",
    "label.display_name_auto_fill": "Nome de exibição (preenchimento automático)",
    "label.domain_name": "Nome do domínio",
    "label.fax_number": "Número de fax",
    "label.general": "GERAL",
    "label.job_title": "Cargo",
    "label.mobile": "Celular",
    "label.name": "Nome",
    "label.pager": "Bip",
    "label.password": "Senha",
    "label.phone": "Telefone",
    "label.postal_code": "CEP",
    "label.profile": "PERFIL",
    "label.repeat_password": "Repetir senha",
    "label.security": "SEGURANÇA",
    "label.second_name_initials": "Iniciais do nome do meio",
    "label.state": "Estado",
    "label.surname": "Sobrenome",
    "label.surname_required": "Sobrenome é obrigatório",
    "label.language": "Idioma",
    "label.general_settings": "Configurações gerais",
    "label.management": "Gerenciamento",
    "label.services": "Serviços",
    "label.backup": "Backup",
    "label.active": "Ativo",
    "label.enabled": "Ativado",
    "label.disabled": "Desativado",
    "label.running": "Em execução",
    "label.queued": "Na fila",
    "label.done": "Concluído",
}


CURATED_TRANSLATIONS: dict[str, str] = {
    "backup.bucket_configuration": "Configuração do bucket",
    "backup.purge_old_configuration": "Remover configuração antiga",
    "backup.purge_old_configurations": "Remover configurações antigas",
    "backup.smart_scan_configuration": "Configuração do SmartScan",
    "backup.tuning_options": "Opções de ajuste",
    "core.subscription.company_name": "Nome da empresa",
    "domain.administration_rights": "Direitos de administração",
    "domain.account_list": "Lista de contas",
    "domain.accounts.totalAccounts": "Total de contas",
    "domain.globalSettings.allowSearchUserFromAllDomains": "Permitir pesquisa de informações de usuários em todos os domínios",
    "domain.mobile_apps": "Aplicativos móveis",
    "label.add_administration_rights": "Adicionar direitos de administração",
    "label.admin_panel_theme_description": "Nesta seção você pode personalizar o painel de administração com o logotipo e a imagem da sua empresa.",
    "label.administration_rights": "Direitos de administração",
    "label.can_access_settings": "Pode acessar as configurações",
    "label.configuration_lbl": "Configuração",
    "label.Cos_list": "Lista de COS",
    "label.cos_list": "Lista de COS",
    "label.creation_date": "Data de criação",
    "label.delegated_administration_title": "Administração delegada",
    "label.delete_configuration": "EXCLUIR CONFIGURAÇÃO",
    "label.disable_delegated_administration": "Desativar administração delegada para {{name}}?",
    "label.duplicate": "DUPLICAR",
    "label.enable_the_mobile_dos_protection_service": "Ativar serviço de proteção contra DOS móvel",
    "label.end_user_theme_description": "Nesta seção você pode personalizar o WebApp com o logotipo e a imagem da sua empresa.",
    "label.export_configuration": "EXPORTAR CONFIGURAÇÃO",
    "label.forgotten_password": "Senha esquecida",
    "label.general_options": "Opções gerais",
    "label.handle_accounts": "Contas tratadas (-1 para ilimitado)",
    "label.i_am_looking_for_this_account": "Buscar conta...",
    "label.i_am_looking_for_this_domain": "Buscar domínio...",
    "label.i_m_looking_for_the_session": "Buscar sessão...",
    "label.active_sessions": "Sessões ativas",
    "label.end_session": "ENCERRAR SESSÃO",
    "label.mobile_app": "Aplicativo móvel",
    "label.mobile_dos_protection": "Proteção contra DOS móvel",
    "label.mobile_password": "Senha móvel",
    "label.mailing_options": "Opções de e-mail",
    "label.mailbox_quota_limit_gb": "Limite de cota da caixa postal (GB)",
    "label.new_volume_config": "CONFIGURAÇÃO",
    "label.not_set": "Não definido",
    "label.notes": "Observações",
    "label.quota.source.global": "Cota herdada da configuração global",
    "label.one_time_password_management": "Gerenciamento de senha de uso único (OTP)",
    "label.password_and_repeat_password_not_match": "As senhas não coincidem",
    "label.password_length_msg": "A senha deve ter mais de 5 caracteres",
    "label.scroll_down_to_view_other_items": "Role para baixo para ver outros itens",
    "label.select_a_bucket_configuration": "Selecione uma configuração de bucket",
    "label.session_id": "ID da sessão",
    "label.link": "VINCULAR",
    "label.virtualhost_avaibility_helpertext": "Para tornar o host virtual disponível, a configuração do nginx deve ser recarregada primeiro em todos os proxies.",
    "label.what_is_a_gal": "O que é GAL?",
    "label.you_have_deleted_the_configuration": "Você excluiu a configuração",
    "label.you_have_exported_the_configuration": "Você exportou a configuração",
    "label.you_have_imported_the_configuration": "Você importou a configuração",
    "label.you_have_no_sufficient_administrationr_rights_to_see_this_section": "Você não tem direitos de administração suficientes para ver esta seção",
    "mta.enable_simple_authentication_and_security_layer": "Ativar camada simples de autenticação e segurança",
    "mta.inbound_flow_and_security": "Fluxo de entrada e segurança",
    "mta.outbound_flow": "Fluxo de saída",
    "cos.general_options": "Opções gerais",
    "mta.tls_security_level": "Nível de segurança TLS",
    "backup.archive_user_metadata_folder_in_the_remote_backup": "Arquivar pasta de metadados do usuário no backup remoto",
    "backup.back_delete_account_warning_message": "Se você definir 0, as <strong>contas</strong> serão mantidas no backup para sempre",
    "backup.backup_configuration": "Configuração de backup",
    "backup.backup_is_enable_at_the_startup": "Backup ativado na inicialização",
    "backup.backup_is_enabled_at_startup": "Backup ativado na inicialização",
    "backup.backup_path": "Caminho do backup",
    "backup.config.scheduleBackupPurge": "Agendar limpeza de backup",
    "backup.data_retention_policies": "Políticas de retenção de dados",
    "backup.external_volume": "Volume externo",
    "backup.force_backup_purge_now": "Forçar limpeza do backup agora",
    "backup.include_server_configuration": "Incluir configuração do servidor",
    "backup.initialising_backup_check_your_notifications_for_updates": "INICIALIZANDO BACKUP... VERIFIQUE AS NOTIFICAÇÕES PARA ACOMPANHAR O ANDAMENTO",
    "backup.initialize_backup": "Inicializar backup",
    "backup.keep_delete_accounts_in_backup": "Manter contas excluídas no backup",
    "backup.keep_deleted_account_in_the_backup": "Manter conta excluída no backup",
    "backup.keep_deleted_item_in_backup": "Manter itens excluídos no backup",
    "backup.keep_delted_items_backup": "Manter itens excluídos no backup",
    "backup.local_volume_reload_if_you_changed_this_value": "Volume local (recarregue se alterar este valor)",
    "backup.manage_external_volume": "Gerenciar volume externo",
    "backup.max_operations_account": "Máximo de operações por conta",
    "backup.max_waiting_time": "Tempo máximo de espera",
    "backup.max_waiting_time_ms": "Tempo máximo de espera (ms)",
    "backup.maximum_metadata_size_mb": "Tamanho máximo dos metadados (MB)",
    "backup.maximum_operation_per_account": "Máximo de operações por conta",
    "backup.metatdata_size": "Tamanho dos metadados",
    "backup.minimum_space_threshold": "Limite mínimo de espaço",
    "backup.schedule": "Agendamento",
    "backup.schedule_automatic_retention_policies": "Agendar políticas automáticas de retenção",
    "backup.schedule_smart_scan": "Agendar SmartScan",
    "backup.schedule_smartscan": "Agendar SmartScan",
    "backup.set_backup_forever_msg": "Se você definir 0, os dados serão mantidos no backup para sempre",
    "backup.set_external_volume": "Definir volume externo",
    "backup.space_threshold_mb": "Limite de espaço (MB)",
    "backup.start_service": "Iniciar serviço",
    "backup.stop_service": "Parar serviço",
    "backup.store_server_configurations_in_the_backup": "Armazenar configuração do servidor no backup",
    "backup.the_service_is": "O serviço está",
    "backup.thread_number_for_accounts": "Número de threads para contas",
    "banner.maintenance-expired-empty-max-version-label": "Sua manutenção suporta versões do Carbonio até Não definido. Versão instalada: {{carbonioVersion}}. Não atualize além de Não definido para evitar interrupção do serviço. Para continuar recebendo atualizações, entre em contato com seu provedor de licenciamento para renovar a manutenção. Última atualização da licença: {{updateTime}}",
    "banner.maintenance-expired-label": "Sua manutenção suporta versões do Carbonio até {{maxCarbonioVersion}}. Versão instalada: {{carbonioVersion}}. Não atualize além de {{maxCarbonioVersion}} para evitar interrupção do serviço. Para continuar recebendo atualizações, entre em contato com seu provedor de licenciamento para renovar a manutenção. Última atualização da licença: {{updateTime}}",
    "banner.maintenance-invalid-label": "Versão máxima suportada: {{maxCarbonioVersion}}. Entre em contato com seu provedor de licenciamento para atualizar ou renovar a manutenção. Última atualização da licença: {{updateTime}}",
    "buckets.invalid_prefix": "O prefixo não pode conter espaços. São permitidas letras de a-z, A-Z e os caracteres especiais /-.",
    "buckets.invalid_volume_name": "O nome do volume é obrigatório.",
    "buckets.invalid_volume_path": "O caminho é obrigatório.",
    "button.refresh_page": "ATUALIZAR",
    "commons.data_already_sent_to_the_user": "DADOS JÁ ENVIADOS AO USUÁRIO",
    "core.subscription.contact_provider": "Para atualizar sua licença, entre em contato com o provedor do serviço.",
    "core.subscription.last_validation_check_tooltip": "Esta data representa o último dia em que a licença foi validada pelo serviço de assinatura da Zextras. Como esta é uma assinatura Pay Per Use (PPU), o sistema informa automaticamente o uso diário para o serviço de assinatura da Zextras. Nenhuma ação do usuário é necessária enquanto a comunicação estiver funcionando. Se o sistema não conseguir contatar o serviço, será aplicado um período de carência de 7 dias, renovado automaticamente sempre que o serviço for contatado com sucesso.",
    "core.subscription.maxCarbonioVersion": "Versão máxima do Carbonio",
    "core.subscription.modal.warning": "Você está tentando desativar o token atual. Isso desativará todos os recursos habilitados.",
    "core.subscription.next_validation_deadline_tooltip": "Esta data representa o último dia em que a licença permanecerá totalmente funcional se os dados de uso não forem enviados ao serviço de assinatura da Zextras. Como esta é uma assinatura Pay Per Use (PPU), o sistema informa automaticamente o uso diário para o serviço de assinatura da Zextras. Nenhuma ação do usuário é necessária enquanto a comunicação estiver funcionando. Se o sistema não conseguir contatar o serviço, será aplicado um período de carência de 7 dias, renovado automaticamente sempre que o serviço for contatado com sucesso.",
    "core.subscription.total_accounts": "Total de contas ativas",
    "cos.add_forwarded_invites_to_calendar": "Adicionar automaticamente compromissos encaminhados ao calendário",
    "cos.add_invites_with_publish_method": "Adicionar convites com método PUBLISH",
    "cos.allow_sending_cancellation_mail": "Permitir envio de e-mail de cancelamento",
    "cos.auto_decline_if_inviter_is_blacklisted": "Recusar automaticamente se o remetente estiver na lista de bloqueio",
    "cos.auto_delete_duplicate_messages": "Excluir automaticamente mensagens duplicadas",
    "cos.days_hours_minutes_sec": "Dias / Horas / Minutos / Seg",
    "cos.default_charset": "Conjunto de caracteres padrão",
    "cos.default_view.work_week": "Visualização de semana útil",
    "cos.email_message_lifetime": "Tempo de vida das mensagens de e-mail",
    "cos.email_retention_policy": "Política de retenção de e-mail",
    "cos.enable_failed_login_lockout": "Ativar bloqueio por falhas de login",
    "cos.enable_past_due_reminders": "Ativar lembretes de compromissos vencidos",
    "cos.failed_login_policy": "Política de falhas de login",
    "cos.features.allowSetupDeferralDuringGracePeriodInfo": "Usuários podem adiar o assistente por tempo limitado. O aviso reaparecerá a cada login até que a configuração seja concluída ou o período de carência expire.",
    "cos.features.allowSetupFromUntrustedNetworksInfo": "Permite que usuários sem OTP concluam o assistente de configuração 2FA no login a partir de redes não confiáveis. Desative esta opção para bloquear o acesso de redes não confiáveis até que o 2FA já esteja configurado.",
    "cos.features.allowUsersToConfigure2FA": "Permitir que usuários configurem 2FA",
    "cos.features.allowUsersToConfigure2FAInfo": "Usuários poderão configurar e gerenciar a senha de uso único (OTP) nas configurações do perfil.",
    "cos.files_account_quota_gb": "Cota da conta para arquivos (GB)",
    "cos.forwarding": "Encaminhamento",
    "cos.limit_user_specified_forwarding_addresses": "Limite de endereços de encaminhamento definidos pelo usuário (caracteres)",
    "cos.limt_serverpool_avaiable_create_user": "Limitar pool de servidores disponível para criar novos usuários neste COS",
    "cos.mails_account_quota_gb": "Cota da conta para e-mails (GB)",
    "cos.max_contacts_allowed_in_the_folder": "Máximo de contatos permitidos na pasta",
    "cos.max_user_specific_forwarding_address": "Máximo de endereços de encaminhamento por usuário",
    "cos.maximum_password_age": "Idade máxima da senha (dias)",
    "cos.maximum_password_length": "Comprimento máximo da senha",
    "cos.minimum_duration_of_time_between_quota_warnings": "Intervalo mínimo entre avisos de cota",
    "cos.minimum_lower_case_characters": "Mínimo de caracteres minúsculos",
    "cos.minimum_mail_polling_interval": "Intervalo mínimo de verificação de e-mail",
    "cos.minimum_number_of_unique_password_history": "Número mínimo de senhas únicas no histórico",
    "cos.minimum_numeric_characters_or_punctuation_symbols": "Mínimo de caracteres numéricos ou símbolos de pontuação",
    "cos.minimum_numeric_chracters": "Mínimo de caracteres numéricos",
    "cos.minimum_password_age": "Idade mínima da senha (dias)",
    "cos.minimum_password_length": "Comprimento mínimo da senha",
    "cos.minimum_punctuation_symbols": "Mínimo de símbolos de pontuação",
    "cos.minimum_upper_case_characters": "Mínimo de caracteres maiúsculos",
    "cos.notify_changes_by_delegated_access": "Notificar alterações feitas por contas delegadas",
    "cos.number_of_consecutive_failed_login_allowed": "Número de falhas de login consecutivas permitidas",
    "cos.password_set_to_use_external_authentication_information_msg": "Estas configurações não afetam senhas de usuários em domínios configurados para autenticação externa",
    "cos.percentage_threshold_for_quota_warning": "Percentual para mensagens de aviso de cota (%)",
    "cos.polling_interval": "Intervalo de verificação",
    "cos.preferences.allowTheUserToAskForAReadReceipt": "Permitir que o usuário solicite confirmação de leitura",
    "cos.prevent_user_from_changing_password": "Impedir que o usuário altere a senha",
    "cos.quota_warning_message_template": "Modelo da mensagem de aviso de cota",
    "cos.quotas": "Cotas",
    "cos.read_receipt_settings": "Configurações de confirmação de leitura",
    "cos.reject_common_passwords": "Rejeitar senhas comuns",
    "cos.save_to_Sent": "Salvar em enviados",
    "cos.select_cos_to_include_in_domain": "Selecione um COS para incluir neste domínio",
    "cos.session_idle_timeout": "Tempo limite de sessão ociosa",
    "cos.spam_message_lifetime": "Tempo de vida das mensagens de spam",
    "cos.time_to_lockout_account": "Tempo para bloquear a conta",
    "cos.time_window_failed_logins_must_occur_to_lock_account": "Janela de tempo em que as falhas de login devem ocorrer para bloquear a conta:",
    "cos.trashed_message_lifetime": "Tempo de vida das mensagens na lixeira",
    "cos.upload_max_size_per_file": "Tamanho máximo permitido para cada anexo (bytes)",
    "cos.use_ical_delegation_model_for_shared_calendars": "Usar modelo de delegação iCal para calendários compartilhados",
    "cos.enable_auto_add_contacts": "Ativar adição automática de contatos",
    "cos.use_gal_to_auto_fill": "Usar GAL para preenchimento automático",
    "cos.user_can_specify_forwarding_address": "Usuário pode especificar endereço de encaminhamento",
    "cos.user_can_specify_mail_forwarding_filter": "Usuário pode especificar filtro de encaminhamento de e-mail",
    "cos.view_mail_as_html": "Visualizar e-mail como HTML quando possível",
    "cos_quota.click_to_revert": "Clique para reverter para o valor herdado",
    "domain.accounts.allowSetupDeferralDuringGracePeriodInfo": "Usuários podem adiar o assistente por tempo limitado. O aviso reaparecerá a cada login até que a configuração seja concluída ou o período de carência expire.",
    "domain.accounts.allowSetupFromUntrustedNetworksInfo": "Permite que usuários sem OTP concluam o assistente de configuração 2FA no login a partir de redes não confiáveis. Desative esta opção para bloquear o acesso de redes não confiáveis até que o 2FA já esteja configurado.",
    "domain.accounts.allowUsersToConfigure2FA": "Permitir que usuários configurem 2FA",
    "domain.accounts.allowUsersToConfigure2FAInfo": "Usuários poderão configurar e gerenciar a senha de uso único (OTP) nas configurações do perfil.",
    "domain.certificate_content_error": "O certificado do domínio, a cadeia CA ou a chave privada é inválida",
    "domain.certificate_content_error_without_ca_chain": "O certificado do domínio ou a chave privada é inválida",
    "domain.distributionList.addOwnersByEmail": "Adicionar proprietários por endereço de e-mail",
    "domain.distributionList.blankEmailErrorMsg": "Informe pelo menos um endereço de e-mail",
    "domain.distributionList.invalidEmailErrorMsg": "A conta não existe. Verifique a grafia e tente novamente.",
    "domain.distributionList.members.areYouSureDeleteMember": "Tem certeza de que deseja remover <bold>{{name}}</bold> da lista de membros?",
    "domain.distributionList.owners.areYouSureDeleteOwner": "Tem certeza de que deseja remover <bold>{{name}}</bold> da lista de proprietários?",
    "domain.distributionList.sendAs": "ENVIAR COMO",
    "domain.distributionList.sendAs.addAccount": "ADICIONAR CONTA",
    "domain.distributionList.sendAs.addSendersByEmail": "Adicionar remetentes por endereço de e-mail",
    "domain.distributionList.sendAs.authorizedSendersList": "Remetentes autorizados desta lista de distribuição",
    "domain.distributionList.sendAs.managePermissionDescriptionMsg": "Permitir que outras pessoas enviem e-mails como esta lista de distribuição",
    "domain.distributionList.sendAs.permissionLevelSendMsg": "Permite que um usuário envie e-mails que parecem vir diretamente de uma lista de distribuição, sem indicar quem realmente enviou",
    "domain.distributionList.sendAs.permissionLevelSendOnBehalfOfMsg": "Permite que um usuário envie um e-mail em que o destinatário veja, por exemplo, \"nome.sobrenome@mail.com em nome de uma lista de distribuição\"",
    "domain.distributionList.sendAs.removeAuthorizedSender": "Remover remetente autorizado",
    "domain.distributionList.sendAs.removeAuthorizedSenderMsg": "Tem certeza de que deseja remover <bold>{{name}}</bold> com nível de permissão <bold>{{permission}}</bold> da lista?",
    "domain.distributionList.sendAs.sendAs": "Enviar como",
    "domain.distributionList.sendAs.sendOnBehalfOf": "Enviar em nome de",
    "domain.distributionList.sendAs.senderAddedSuccessfully": "Remetente autorizado adicionado com sucesso",
    "domain.distributionList.sendAs.senderRemovedSuccessfully": "Remetente autorizado removido com sucesso",
    "domain.distributionList.sendTo": "ENVIAR PARA",
    "domain.distributionList.sendTo.acceptMessageFrom": "Aceitar mensagem de",
    "domain.distributionList.sendTo.addSendersByEmail": "Adicionar remetentes por endereço de e-mail",
    "domain.distributionList.sendTo.authorizedSendersToList": "Remetentes autorizados para esta lista de distribuição",
    "domain.distributionList.sendTo.managePermissionDescriptionMsg": "Controlar quem pode enviar e-mails para esta lista de distribuição",
    "domain.editAccount.invalidaEmailError": "Um ou mais endereços de e-mail são inválidos.",
    "domain.editAccount.restoreOtpInfo": "Antes de continuar, confirme que o usuário solicitou esta ação. Se suspeitar de ataque não autorizado, não restaure.",
    "domain.i_want_to_see_this_domain": "Quero ver este domínio",
    "domain.jail_duration": "Duração do bloqueio (ms)",
    "domain.mailSpaceQuotaThresholdError.description": "O limite de cota de espaço de e-mail deve estar entre 0 e 100",
    "domain.mail_space_quota_threshold_warning": "Aviso do limite de cota de espaço de e-mail (%)",
    "domain.mailingList.canReceive": "Pode receber",
    "domain.mailingList.cantReceive": "Não pode receber",
    "domain.page_size": "Tamanho da página",
    "domain.receiver_of_quota_warning_email": "Destinatário do aviso de cota (e-mail)",
    "domain.the_account_has_been_successfully_created": "A conta foi criada com sucesso",
    "domain.type_here_a_domain": "Digite um domínio aqui",
    "domain.unit_measure_days": "Dias",
    "domain.globalSettings.allowSearchUserFromAllDomains": "Permitir pesquisa de informações de usuários em todos os domínios",
    "domains.generalSettings.AllowSearchUserFromSpecificDomains": "Pesquisar usuários em domínios específicos",
    "hsm.all_primary_volume_used_source_msg": "Todos os volumes primários serão usados como origem por padrão. Ou selecione manualmente outros volumes.",
    "hsm.all_secondary_volume_used_source_msg": "O volume secundário atual será usado como destino. Ou selecione manualmente outros volumes.",
    "hsm.days": "Dias",
    "hsm.default_hsm_policy_warning_message": "Pelo menos uma política sempre permanecerá ativa. Se você excluir a última, outra será gerada",
    "hsm.delete_hsm_policy_confirm_msg_1": "Se você excluir esta política HSM, não poderá restaurá-la. Deseja excluir a política HSM?",
    "hsm.destination_volume": "Volume de destino",
    "hsm.larger_size": "Maior (tamanho)",
    "hsm.minimum_space_threshold": "Limite mínimo de espaço",
    "hsm.schedule": "Agendamento",
    "hsm.select_manually_source_volumes": "Selecionar volumes de origem manualmente",
    "hsm.smaller_size": "Menor (tamanho)",
    "hsm.source_volume": "Volume de origem",
    "hsm.this_function_allow_save_disk_copy_msg": "Esta função permite economizar espaço em disco armazenando uma única cópia de um item.",
    "hsm.volume_already_selected_in_destination": "Volume já selecionado como destino",
    "hsm.volume_already_selected_in_source": "Volume já selecionado como origem",
    "label.2fa-policy-updated-successfully": "As configurações foram aplicadas a todos os serviços",
    "label.DELETE": "EXCLUIR",
    "label.This account has Administration rights for": "Esta conta tem direitos de administração para",
    "label.accountQuota.banner.overQuota": "Esta conta atingiu o limite de armazenamento. Aumente a cota de armazenamento imediatamente ou notifique o usuário para liberar espaço.",
    "label.accountQuota.banner.thresholdReached": "Esta conta está próxima do limite de armazenamento. Aumente a cota de armazenamento ou notifique o usuário para liberar espaço.",
    "label.account_created_successfully": "A conta foi criada com sucesso",
    "label.account_disable_correctly": "A conta foi desativada corretamente.",
    "label.account_password_setting_note_for_external_authentication": "As configurações abaixo não afetam senhas definidas por usuários em domínios configurados para autenticação externa. As alterações feitas aqui substituirão as configurações de COS para senha e bloqueio por falhas de login.",
    "label.account_remove_correctly": "A conta foi removida corretamente.",
    "label.accounts_list": "Contas de e-mail",
    "label.active_sync_active_paused": "O ActiveSync está ativo / pausado",
    "label.add_appointments_when_invited": "Adicionar automaticamente compromissos quando o usuário for convidado",
    "label.add_to_the_list": "Adicionar à lista",
    "label.add_virtual_host_name": "Digite um novo nome de host virtual e clique em “Adicionar +” para adicioná-lo à lista",
    "label.allow_restore_message": "Permitir que o usuário restaure mensagens",
    "label.allow_send_receive": "Permitir envio/recebimento",
    "label.always_send_read_receipt": "Sempre enviar confirmação de leitura",
    "label.appointment_reminder_in_minutes": "Lembrete de compromisso em minutos",
    "label.appointments_default_duration": "Duração padrão dos compromissos",
    "label.ask_me": "Perguntar",
    "label.are_you_sure_delete_distribution_list": "Tem certeza de que deseja excluir <bold>{{name}}</bold>?",
    "label.are_you_sure_deleting_cos": "Tem certeza de que deseja excluir esta classe de serviço?",
    "label.aware_of_doing_device_factory_settings": "Estou ciente do que estou fazendo e quero restaurar para as configurações de fábrica",
    "label.background_description": "Cole a URL da imagem para a página de login. Use arquivo JPG ou PNG, com resolução mínima de 1280x720 pixels, proporção 16:9 e menor que 800 KB.",
    "label.background_for_the_login_page": "Imagem de fundo da página de login",
    "label.background_login_page": "Imagem de fundo do login",
    "label.backup_at_startup": "Backup na inicialização",
    "label.backup_enabled": "Ativar / desativar backup",
    "label.backup_primarybar_tooltip": "Gerencie seus <bold>serviços de backup</bold>, visualize <bold>status</bold>, <bold>lista de servidores</bold> ou <bold>importe um backup existente</bold>.",
    "label.backup_space": "Espaço de backup",
    "label.block_send": "Bloquear envio",
    "label.block_send_receive": "Bloquear envio/recebimento",
    "label.bucket_create_button": "CRIAR",
    "label.bucket_verification_failed_message": "Falha na verificação. Não foi possível testar a configuração do bucket. {{bucketType}} não é compatível com esta conexão (ID: {{bucketId}})",
    "label.can_receive": "Pode receber",
    "label.can_receive_email": "Pode receber e-mail",
    "label.cancel_operation_sucess": "A operação {{name}} foi cancelada com sucesso",
    "label.cancel_operations_message": "Tem certeza de que deseja CANCELAR esta operação? <br /> Ao clicar em CANCELAR OPERAÇÃO, ela será <br /> removida da fila de operações.",
    "label.certificate_alert_helperText": "O certificado ficará disponível depois que o Proxy for reiniciado",
    "label.certificate_available_after_proxy_restart": "O certificado ficará disponível depois que o Proxy for reiniciado",
    "label.certificate_request_success": "Processando. Os resultados serão notificados aos destinatários globais e de domínio",
    "label.change_save_success_msg": "A alteração foi salva com sucesso",
    "label.changes_have_been_saved": "As alterações foram salvas",
    "label.calendar_options": "Opções de calendário",
    "label.check_new_mail_every": "Verificar novos e-mails a cada",
    "label.close_domain": "FECHAR DOMÍNIO",
    "label.close_the_account": "Fechar conta",
    "label.contact_options": "Opções de contato",
    "label.connection_is_created_verify_connector_fail": "CONECTOR CRIADO, MAS A VERIFICAÇÃO FALHOU",
    "label.connector_is_not_created_and_verification_failed": "CONECTOR NÃO CRIADO E VERIFICAÇÃO FALHOU",
    "label.copyrights_theme_note": "As informações de direitos autorais aparecerão no rodapé da caixa de login",
    "label.cos_not_included_for_domain_notes": "Não há COS incluído para este domínio. Selecione um no menu suspenso e clique em \"DUPLICAR\" ou \"VINCULAR\"",
    "label.cos_primarybar_tooltip": "Visualize e gerencie detalhes das suas <bold>Classes de Serviço</bold>, <bold>recursos, pools de servidor</bold> e <bold>configurações avançadas</bold>.",
    "label.create": "CRIAR",
    "label.create_Cos_list_msg": "Você pode criar um novo COS clicando no botão <bold>Criar</bold> no menu superior",
    "label.create_account_button": "CRIAR CONTA",
    "label.create_account_list_msg": "Você pode criar uma nova conta clicando no botão <bold>Criar</bold> no canto superior esquerdo ou no botão Adicionar (<bold>+</bold>) aqui em cima",
    "label.create_another_account": "CRIAR OUTRA CONTA",
    "label.create_distribution_list_msg": "Você pode criar uma nova lista de distribuição clicando no botão <bold>Criar</bold> no canto superior esquerdo ou no botão Adicionar (<bold>+</bold>) aqui em cima",
    "label.create_domain_list_msg": "Você pode criar um novo domínio clicando no botão <bold>Criar</bold> no menu superior",
    "label.create_galsync_account_success_msg": "Você criou a conta GALSync",
    "label.create_otp_list_msg": "Você pode criar um novo OTP clicando no botão <bold>NOVO OTP</bold> aqui em cima",
    "label.create_resource_msg": "Você pode criar um novo recurso clicando no botão <bold>Criar</bold> no canto superior esquerdo ou no botão Adicionar (<bold>+</bold>) aqui em cima",
    "label.days": "Dias",
    "label.days_hours_minutes_sec": "Dias / Horas / Minutos / Seg",
    "label.default_appointment_visibility": "Visibilidade padrão dos compromissos",
    "label.default_calendar_view": "Visualização padrão do calendário",
    "label.default_charset": "Conjunto de caracteres padrão",
    "label.delegate_send_settings": "Configurações de envio delegado",
    "label.delegated_administration_helper_message": "A administração delegada para {{domainName}} será desativada. <br /> Você tem duas opções: <br /><br /> 1. Remover todas as ACLs (listas de controle de acesso) do domínio. <br /> 2. Manter as ACLs no domínio, mas desativar os direitos associados. <br /><br /> Como deseja prosseguir?",
    "label.delete_all_certificates_content": "Você está excluindo todos os certificados.<br /> Tem certeza de que deseja excluir?",
    "label.delete_bucket_fail": "{{name}} não foi removido",
    "label.delete_bucket_sucess": "{{name}} foi removido",
    "label.delete_button": "EXCLUIR",
    "label.delete_cos_instruction_msg": "Se clicar em SIM, EXCLUIR, o DefaultCOS substituirá o COS excluído.",
    "label.deleting_account_content_1": "Tem certeza de que deseja excluir <bold>{{name}}</bold>?",
    "label.deleting_account_content_2": "Excluir a conta <bold>apagará PERMANENTEMENTE</bold> todos os dados.",
    "label.deleting_account_name": "Você está excluindo a conta {{name}}",
    "label.deleting_account_warning_content": "Excluir uma conta de sistema pode afetar a estabilidade do sistema.",
    "label.destroy": "EXCLUIR",
    "label.destroy_account_button": "SIM, EXCLUIR",
    "label.disable": "desativar",
    "label.distribution_list_already_in_list_error": "A lista de distribuição / usuário já está na lista",
    "label.domain": "domínio",
    "label.domain_certificate_private_key": "Chave privada do domínio",
    "label.domain_support_delegated_administration": "Este domínio oferece suporte à administração delegada",
    "label.domains_that_use_this_cos_as_default": "Domínios que usam este COS como padrão",
    "label.enable": "ativar",
    "label.enable_current_helptext": "Ativar esta opção desativará o volume ativo atual.",
    "label.disclaimer": "Aviso legal",
    "label.domain_system_notifications": "Notificações do sistema do domínio",
    "label.enable_disclaimers_for_all_domains": "Aviso legal obrigatório para todos os domínios",
    "label.enable_disclaimers_for_this_domain": "Ativar aviso legal para este domínio",
    "label.enable_global_enforce_external_auth_ldap": "Você deve ativar primeiro a imposição global de autenticação externa (LDAP/AD)",
    "label.end_user_title": "USUÁRIO FINAL",
    "label.enduser_login_redirect_url": "Destino de redirecionamento após login (URL)",
    "label.enter_valid_email_address": "Informe um endereço de e-mail válido",
    "label.error_loading_cos_list": "Falha ao carregar a lista de COS. Tente novamente.",
    "label.ext_volume": "Volume externo",
    "label.external_password_change_listener": "Endpoint usado para alteração de senha",
    "label.failed": "Falhou",
    "label.favicon_description": "Cole a URL do favicon para a página de login. Use um arquivo ICO com dimensão de 32x32 pixels.",
    "label.features": "Recursos",
    "label.files_space_limit_gb": "Limite de espaço para arquivos (GB)",
    "label.files_space_usage": "Uso de espaço por arquivos",
    "label.filter_by_device_type_account": "Filtrar por tipo de dispositivo, conta e status",
    "label.forwarding": "Encaminhamento",
    "label.gal_folder_name": "Nome da pasta GAL",
    "label.has_backup": "Tem backup",
    "label.here_will_be_shown_the_attribute_value": "O valor do atributo será exibido aqui",
    "label.how_many_accounts_handled": "Quantas contas são tratadas? (-1 para ilimitado)",
    "label.index_volume": "Este é um volume de índice",
    "label.init_domain": "INICIALIZAR DOMÍNIO",
    "label.invalid_email_address": "Endereço de e-mail inválido",
    "label.keep_acls_&_disbale_rigths": "<bold>MANTER</bold> ACLs, DESATIVAR DIREITOS",
    "label.lockout": "Bloqueio",
    "label.login": "Login",
    "label.login_is_disabled": "Login desativado",
    "label.login_verified_button_title": "LOGIN VERIFICADO",
    "label.login_verify_button_title": "LOGIN E VERIFICAR",
    "label.logo_description": "Cole a URL do logotipo para a página de login. Use arquivo SVG ou PNG com fundo transparente e dimensão de 240x120 pixels.",
    "label.logo_for_login_page": "Logotipo da página de login",
    "label.logo_redirection_title": "Ao clicar no logotipo, os usuários serão redirecionados para...",
    "label.mail_over_quota_criteria": "Critério de e-mail acima da cota",
    "label.mailbox_space_usage": "Uso de espaço da caixa postal",
    "label.manage_external_volume_and_move_all": "GERENCIAR VOLUME EXTERNO e mover todos os itens para o caminho local",
    "label.mandatory_disclaimer_are_enable_for_all_domain": "Os avisos legais obrigatórios estão ativados para todos os domínios",
    "label.mandatory_disclaimer_are_enable_only_for_outbound_deliveries": "Os avisos legais obrigatórios estão ativados apenas para mensagens de saída",
    "label.mandatory_disclaimer_is_enable_for_this_domain": "O aviso legal obrigatório está ativado para este domínio",
    "label.max_mainbox_quota_for_the_domain_in_gb": "Cota máxima de caixa postal para o domínio (GB) (0=ilimitado)",
    "label.max_mainbox_quota_for_the_mails_in_gb": "Cota máxima de caixa postal para e-mails (GB)",
    "label.max_manageable_account_for_the_domain": "Máximo de contas gerenciáveis para o domínio (0=ilimitado)",
    "label.max_quota_per_account_in_this_domain": "Cota máxima por conta neste domínio (GB)",
    "label.maximum_3_digits_allowed_decimal_point": "Máximo de 3 dígitos permitidos após o ponto decimal",
    "label.maximum_conflict": "Conflito máximo",
    "label.maximum_conflict_allowed": "Conflito máximo permitido",
    "label.maximum_handled_accounts": "Máximo de contas tratadas",
    "label.maximum_of_requests_allowed": "Máximo de solicitações permitidas",
    "label.metadata_space": "Espaço de metadados",
    "label.never_send_read_receipt": "Nunca enviar confirmação de leitura",
    "label.never_show_this_again": "NUNCA MOSTRAR NOVAMENTE",
    "label.new_volume_button": "NOVO VOLUME",
    "label.new_volume_create": "CRIAR",
    "label.notification_error_msg": "Informe um endereço de e-mail válido.",
    "label.notification_primarybar_tooltip": "Visualize suas <bold>notificações</bold>, marque como <bold>lidas</bold> ou <bold>copie</bold> para compartilhar.",
    "label.notification_sender": "Remetente da notificação",
    "label.number_of_results_exceeded_the_limit": "O número de resultados excedeu o limite. Use a pesquisa para refinar os resultados.",
    "label.only_allow_outbound_disclaimers": "Permitir avisos legais apenas em mensagens de saída",
    "label.only_there_users": "Somente estes usuários",
    "label.operation_now_in_queue": "A operação está agora na fila",
    "label.owners_description_msg_1": "Proprietários podem adicionar e remover membros, alterar nome de exibição e descrição, alterar visibilidade da lista (por exemplo, ocultar na GAL), alterar propriedade e modificar comportamento de inscrição/cancelamento.",
    "label.path": "Caminho",
    "label.percentage_maximum_conflict": "% de conflito máximo",
    "label.percentage_maximum_conflict_allowed": "% de conflito máximo permitido",
    "label.please_add_ldap_url_endpoint_first": "Para ativar isto, adicione primeiro um endpoint de URL LDAP",
    "label.primary_volume": "Este é um volume primário",
    "label.privacy_primarybar_tooltip": "Gerencie <bold>configurações de privacidade</bold>, como <bold>relatórios de dados, logs de erro</bold> e <bold>pesquisas</bold>.",
    "label.private": "Privado",
    "label.public": "Público",
    "label.public_service_hostname": "Nome do host do serviço público",
    "label.public_service_port": "Porta do serviço público",
    "label.public_service_protocol": "Protocolo do serviço público",
    "label.quota.source.domain": "Cota herdada das configurações do domínio",
    "label.read_options": "Opções de leitura",
    "label.read_receipt_settings": "Configurações de confirmação de leitura",
    "label.reason": "Motivo",
    "label.re_init_domain": "REINICIALIZAR DOMÍNIO",
    "label.receiving_mails": "Recebimento de e-mails",
    "label.reset_domain_whitelabel_settings": "Redefinir configurações de marca branca de {{name}}",
    "label.reset_global_whitelabel_settings": "Redefinir configurações globais de marca branca",
    "label.reset_whitelabel_settings_content_1": "Tem certeza de que deseja redefinir as configurações de marca branca?",
    "label.resource_deleted_successfully": "{{resource_name}} foi excluído com sucesso",
    "label.resource_disable_successfully": "{{resource_name}} foi desativado com sucesso.",
    "label.rest_device_warning_msg_1": "Limpar um dispositivo irá restaurá-lo para as configurações de fábrica. Tem certeza de que deseja continuar?",
    "label.restart_jail": "Reiniciar bloqueio",
    "label.restore_account_has_added_operation_queue": "A restauração da conta foi adicionada à fila de operações com sucesso",
    "label.restore_select_account_row_2": "<bold>Observe</bold> que todos os e-mails, compromissos, contatos e configurações da conta serão restaurados como estavam no timestamp escolhido.",
    "label.retention_period": "Período de retenção (valor)",
    "label.run_only": "EXECUTAR APENAS (PULAR CRIAÇÃO)",
    "label.save_it_only_deligates_folder": "Salvar apenas na pasta do delegado",
    "label.save_it_only_in_folder": "Salvar apenas na pasta {{email}}",
    "label.save_it_only_in_sender_folder": "Salvar em {{email}} e na pasta do delegado",
    "label.search_an_account": "Pesquisar uma conta",
    "label.search_for_a_domain": "Pesquisar um domínio",
    "label.search_for_an_account": "Pesquisar uma conta",
    "label.search_for_user_and_clic_to_add": "Pesquise um usuário e clique no botão ADICIONAR.",
    "label.secondary_volume": "Este é um volume secundário",
    "label.select_an_attribute_to_show_its_value": "Selecione um atributo para exibir seu valor",
    "label.select_an_external_volume": "Selecione um volume externo",
    "label.send_invite_to": "Enviar convite para",
    "label.send_new_members_notification_for_share_assigned_to_this_group": "Enviar aos novos membros uma notificação sobre o compartilhamento/delegação atribuído a este grupo",
    "label.send_notifications_to": "Enviar notificações para...",
    "label.sender": "Remetente",
    "label.sending_mails": "Envio de e-mails",
    "label.sending_options": "Opções de envio",
    "label.set_as_default": "Definir como padrão",
    "label.share_message_to_new_member": "Compartilhar mensagem com novos membros",
    "label.sharing": "COMPARTILHAMENTO",
    "label.sharing_options": "Opções de compartilhamento",
    "label.show_all": "Mostrar todos",
    "label.show_forget_password_link": "Mostrar link \"Esqueci minha senha\" na página de login",
    "label.size_kb": "Tamanho (KB)",
    "label.size_threshold": "Limite de tamanho",
    "label.specified_domain_not_exist": "O domínio especificado não existe",
    "label.stop_operation_sucess": "A operação {{name}} foi interrompida com sucesso",
    "label.stop_operations_message": "Tem certeza de que deseja PARAR esta operação? <br /> Ao clicar em PARAR OPERAÇÃO, ela será interrompida e <br /> removida da fila de operações.",
    "label.storage_hsm_not_licensed": "Não é possível concluir a operação: storages_hsm não licenciado.",
    "label.subject": "Assunto",
    "label.subject_name_cname": "Nome do assunto (registro CNAME)",
    "label.subject_name_fqdn": "Nome alternativo do assunto (FQDN)",
    "label.the_week_starts_on": "A semana começa em",
    "label.this_domain_is_closed": "<text>O domínio <bold> {{domain}} </bold> está fechado</text>",
    "label.this_is_hidden_from_gal": "Esta lista está oculta na GAL",
    "label.this_list_can_receive_email": "Esta lista pode receber e-mails",
    "label.this_list_included_in": "Esta lista está incluída em",
    "label.this_list_is_empty": "Esta lista está vazia.",
    "label.title_theme_note": "O título é o nome que aparecerá na aba do navegador",
    "label.total_acc_rights_with_delete_distribution_list_helper_text": "Esta lista possui <bold>{{totalAccRights}}</bold> direitos de contas compartilhadas. Se você excluí-la, todos os direitos serão perdidos.",
    "label.total_quota_limit_gb": "Cota total (GB)",
    "label.try_local_password_management_ldap": "Desative a opção “Tentar gerenciamento local de senha em caso de falha” ou altere o método de autenticação padrão para editar estes campos",
    "label.type_an_account_add_senders_list": "Digite uma conta para adicioná-la à lista de remetentes",
    "label.type_an_account_dot": "Digite uma conta...",
    "label.type_name_your_domain_will_have": "Digite o nome que seu domínio terá",
    "label.unlimited_quota": "Cota ilimitada",
    "label.upload_paste_private_key": "Envie ou cole sua chave privada",
    "label.user_auto_fill": "usuário (preenchimento automático)",
    "label.user_can_ask_for_forgotten_password_token": "Usuário pode solicitar token de recuperação de senha",
    "label.user_preferences": "PREFERÊNCIAS DO USUÁRIO",
    "label.view_mail": "VISUALIZAR E-MAIL",
    "label.volume_available_unused_Buckets_list_in_backup": "Buckets disponíveis (não utilizados no backup)",
    "label.volume_create": "CRIAR",
    "label.volume_created_msg": "O volume foi criado com sucesso",
    "label.volume_deleted": "Volume excluído com sucesso",
    "label.volume_id": "ID do volume",
    "label.volume_main": "Volume principal",
    "label.volume_name": "Nome do volume",
    "label.volume_path": "Caminho do volume",
    "label.volume_type": "Tipo do volume",
    "label.warning_message": "Ocorreu um aviso durante a operação",
    "label.web_feature": "Recurso web",
    "label.who_can_send_mails_to_list ": "Quem pode enviar e-mails PARA esta lista?",
    "label.who_can_send_mails_to_this_list": "Quem pode enviar e-mails PARA esta lista?",
    "label.wipe_device_factory_settings": "Limpar dispositivo para as configurações de fábrica",
    "label.wiping_device_warning_msg_1": "Limpar um dispositivo irá restaurá-lo para as configurações de fábrica. Tem certeza de que deseja continuar?",
    "label.yes_delete_it": "Sim, excluir",
    "legalHold.show_only_accounts_on_legal_hold": "Mostrar apenas contas em Legal Hold",
    "legal_hold.legal_hold_account_blank_error": "A conta de Legal Hold não pode ficar em branco",
    "legal_hold.legal_hold_status_not_set": "Legal Hold não definido nesta conta",
    "legal_hold.you_must_restore_the_account_before_enable_legal_hold": "Você deve restaurar a conta antes de ativar Legal Hold",
    "many_domain_info_msg": "Muitos domínios. Qual você deseja ver? Comece a digitar para filtrar.",
    "messages.no_content": "Esta mensagem não possui conteúdo de texto",
    "modal.iscurrent_confirm.body_message": "{{currentVolumeName}} é o volume atual.<br />Tem certeza de que deseja <strong>definir {{name}} como volume atual</strong>?",
    "modal.iscurrent_confirm.title": "Você está definindo {{name}} como volume atual",
    "mta.access_list_path": "Caminho da lista de acesso",
    "mta.add_this_prefix_to_spam_mail_subject": "Adicionar este prefixo ao assunto de e-mail de spam",
    "mta.advanced.custom_max_size_mail_messages": "Tamanho máximo personalizado para mensagens de e-mail (MB)",
    "mta.advanced.mail_messages_size": "Tamanho das mensagens de e-mail",
    "mta.advanced.max_size_for_mail_messages": "Tamanho máximo para mensagens de e-mail (MB)",
    "mta.advanced.no_size_limit_for_mail_messages": "Sem limite de tamanho para mensagens de e-mail",
    "mta.advanced.value_0_disables_email_sending": "O valor 0 desativa o envio de e-mail: informe um valor maior que 0",
    "mta.also_check_outbound_messages": "Também verificar mensagens de saída",
    "mta.days": "Dias",
    "mta.dns_blacklist_max_time_to_live": "TTL máximo da blacklist DNS (valor)",
    "mta.enable_or_disable_authentication_for_email_transfer_agent": "Ativar ou desativar autenticação para o agente de transferência de e-mail (MTA)",
    "mta.graylisting_disabled_warning_message": "Esta é uma forma de greylisting; por isso, desative outras formas de greylisting.",
    "mta.include_authenticated_user_information_in_smtp_header_for_outgoing_emails": "Incluir informações do usuário autenticado nos cabeçalhos SMTP de e-mails de saída",
    "mta.max_antivirus_threads": "Máximo de threads do antivírus (valor)",
    "mta.notify_administrators_of_blocked_file_extension_incoming_emails": "Notificar administradores sobre extensões de arquivo bloqueadas em e-mails recebidos",
    "mta.notify_recipients_of_blocked_file_extension_incoming_emails": "Notificar destinatários sobre extensões de arquivo bloqueadas em e-mails recebidos",
    "mta.reject_sender_login_mismatch_or_empty": "Rejeitar login do remetente divergente ou vazio",
    "mta.reject_unlisted_recipient": "Rejeitar destinatário não listado",
    "mta.reject_unlisted_sender": "Rejeitar remetente não listado",
    "mta.remove_virus_difinition_warning_line_1": "Remover uma definição de vírus reduzirá a chance de detectar ameaças potenciais. Esta operação não é reversível",
    "mta.restart_scan": "Reiniciar verificação",
    "mta.select_a_mail_server_to_see_stats": "Selecione um servidor de e-mail para ver as estatísticas",
    "mta.senders_address_must_fully_qualified": "O endereço do remetente deve ser totalmente qualificado",
    "mta.senders_domain": "Domínio do remetente",
    "mta.smtpd_not_valid_error": "Os mapas de login do remetente smtpd não são válidos",
    "mta.smtpd_sender_login_maps": "Mapas de login do remetente smtpd",
    "mta.space_not_allowed_in_antivirus_mirror": "Espaço não permitido no espelho do antivírus",
    "notification.mark_as_read": "Marcar como lida",
    "notification.notification_mark_read_successfully": "Notificação marcada como lida com sucesso",
    "notification.warning": "AVISO",
    "operations.cancel_opearation_btn": "CANCELAR OPERAÇÃO",
    "operations.label.cancel_operation_btn": "CANCELAR OPERAÇÃO",
    "operations.label.stop_operation_btn": "PARAR OPERAÇÃO",
    "operations.stop_opearation_btn": "PARAR OPERAÇÃO",
    "privacy.send_full_error_data": "Enviar dados completos de erro",
    "quarantine.create_quarantine": "CRIAR CONTA DE QUARENTENA",
    "quarantine.delete_and_recrate_quarantine_account_title": "Excluir e recriar conta de quarentena",
    "quarantine.delete_and_recreate_quarantine": "EXCLUIR E RECRIAR CONTA DE QUARENTENA",
    "quarantine.delete_message": "Excluir mensagem",
    "quarantine.destroy_account_recreate_button": "SIM, EXCLUIR E RECRIAR",
    "quarantine.hide_source": "Ocultar origem",
    "quarantine.is_content_email_safe": "O conteúdo do e-mail é seguro?",
    "quarantine.not_quarantine_account": "Ainda não existe conta de quarentena em nenhum domínio. Deseja criar uma conta de quarentena do sistema?",
    "quarantine.please_note_email_contains_dangerous_file_not_be_delivered": "Observe que, se o e-mail ainda contiver um arquivo perigoso, ele não será entregue",
    "quarantine.refresh_list": "ATUALIZAR LISTA",
    "quarantine.show_images": "Mostrar imagens",
    "quarantine.show_source": "Mostrar origem",
    "quarantine.to_make_changes_restart_the_MTA": "Para efetivar as alterações, reinicie o MTA.",
    "quarantine.yes_delete_message": "SIM, EXCLUIR",
    "quota.account_quota_usage.unlimited": "{{used}} de <bold>armazenamento ilimitado</bold> usado",
    "quota.module.wsc": "Chats",
    "select_bucket_or_create_bucket": "Parece que você ainda não configurou um tipo de bucket. Clique no botão \"CRIAR +\" para criar um novo.",
    "select_domain_or_create_new": "Selecione um domínio no menu à esquerda ou clique no botão \"Criar\" para criar um novo.",
    "the_change_will_not_move_the_data": "A alteração não moverá os dados",
    "volume.create_storage_volume": "Criar volume de armazenamento",
    "volume.serverName_volumes_create_mailstores_volume": "{{serverName}} | Criar volume de mailstore",
    "volume.volume_header.path": "Caminho",
    "volume.volume_indexer_header.path": "Caminho",
    "warning.is_current": "Primeiro, defina outro volume como atual.",
    "wsc.section.content.description.attachmentSize": "Defina o tamanho máximo para arquivos compartilhados nos chats.",
    "wsc.section.content.description.createGroup": "Permitir que usuários criem chats com vários participantes.",
    "wsc.section.content.description.createPrivate": "Permitir que usuários iniciem conversas individuais.",
    "wsc.section.content.description.deletionLimit": "Defina o limite de tempo para excluir uma mensagem enviada.",
    "wsc.section.content.description.editLimit": "Defina por quanto tempo uma mensagem pode ser editada após o envio.",
    "wsc.section.content.description.enableAttachments": "Ativar envio de arquivos, imagens e documentos.",
    "wsc.section.content.description.enableFeature": "Ativar mensagens, chats em grupo, chamadas de vídeo e compartilhamento de arquivos.",
    "wsc.section.content.description.enableRecording": "Permitir gravação de chamadas de áudio e vídeo.",
    "wsc.section.content.description.enableVideoCall": "Ativar funcionalidade de chamadas de vídeo.",
    "wsc.section.content.description.enableVirtualBackground": "Permitir que usuários apliquem fundos virtuais durante chamadas de vídeo.",
    "wsc.section.content.description.groupMembers": "Defina o número máximo de usuários por grupo.",
    "wsc.section.content.description.groupPicture": "Limite o tamanho do arquivo para fotos de perfil de grupo.",
    "wsc.section.content.description.presence": "Exibir status online dos usuários ou horário da última visualização.",
    "wsc.section.content.description.readReceipt": "Mostrar aos remetentes quando suas mensagens forem lidas.",
    "wsc.section.content.input.attachmentSize": "Tamanho máximo do anexo em MB",
    "wsc.section.content.input.groupMembers": "Número máximo de membros do grupo",
    "wsc.section.content.input.groupPicture": "Tamanho máximo da foto do grupo em MB",
    "wsc.section.content.select.deleteLimit.zero": "Usuário não pode excluir mensagens enviadas",
    "wsc.section.content.select.deletionLimit": "Limite de tempo para exclusão de mensagem",
    "wsc.section.content.select.editLimit": "Limite de tempo para edição de mensagem",
    "wsc.section.content.select.timeLimit": "Limite de tempo em minutos",
    "wsc.section.content.select.zero.editLimit": "Usuário não pode editar mensagens enviadas",
    "wsc.section.content.toggle.createGroup": "Usuários podem criar chats em grupo",
    "wsc.section.content.toggle.createPrivate": "Usuários podem iniciar chats privados",
    "wsc.section.content.toggle.enableAttachments": "Usuários podem enviar anexos",
    "wsc.section.content.toggle.enableFeature": "Ativar Chat",
    "wsc.section.content.toggle.enableRecording": "Permitir gravação de chamadas",
    "wsc.section.content.toggle.enableVideoCall": "Ativar chamadas de vídeo",
    "wsc.section.content.toggle.enableVirtualBackground": "Ativar fundo virtual",
    "wsc.section.content.toggle.presence": "Mostrar status online dos usuários",
    "wsc.section.content.toggle.readReceipt": "Mostrar confirmações de leitura",
    "wsc.section.header.description.attachments": "Gerenciar compartilhamento de arquivos e limites de anexos.",
    "wsc.section.header.description.chats": "Gerenciar criação de chats e configurações de grupo.",
    "wsc.section.header.description.general": "Gerenciar ativação de recursos principais e aplicativos.",
    "wsc.section.header.description.messaging": "Gerenciar visibilidade dos chats e status dos usuários.",
    "wsc.section.header.description.videocall": "Configurar chamadas de vídeo, gravação e fundos virtuais.",
    "wsc.section.header.title.attachments": "Compartilhamento e anexos",
    "wsc.section.header.title.chats": "Chats privados e em grupo",
    "wsc.section.header.title.messaging": "Mensagens e presença",
    "wsc.section.header.title.videocall": "Chamadas de vídeo",
    "wsc.section.license.warning": "Estas configurações não podem ser alteradas porque sua licença de Chats não é válida.",
}


WORD_TRANSLATIONS: list[tuple[str, str]] = [
    ("ActiveSync", "ActiveSync"),
    ("Z-Push", "Z-Push"),
    ("LDAP", "LDAP"),
    ("SOAP", "SOAP"),
    ("MTA", "MTA"),
    ("COS", "COS"),
    ("SSL", "SSL"),
    ("TLS", "TLS"),
    ("URL", "URL"),
    ("UUID", "UUID"),
    ("ID", "ID"),
    ("Account", "Conta"),
    ("Accounts", "Contas"),
    ("Alias", "Alias"),
    ("Aliases", "Aliases"),
    ("Admin", "Administrador"),
    ("Administrator", "Administrador"),
    ("Advanced", "Avançado"),
    ("Allowed", "Permitido"),
    ("Allow", "Permitir"),
    ("Apply", "Aplicar"),
    ("Attachment", "Anexo"),
    ("Attachments", "Anexos"),
    ("Auth", "Autenticação"),
    ("Backup", "Backup"),
    ("Backups", "Backups"),
    ("Bucket", "Bucket"),
    ("Calendar", "Calendário"),
    ("Cancel", "Cancelar"),
    ("Certificate", "Certificado"),
    ("Certificates", "Certificados"),
    ("Class of Service", "Classe de serviço"),
    ("Close", "Fechar"),
    ("Confirm", "Confirmar"),
    ("Contact", "Contato"),
    ("Contacts", "Contatos"),
    ("Create", "Criar"),
    ("Created", "Criado"),
    ("Delete", "Excluir"),
    ("Description", "Descrição"),
    ("Detail", "Detalhe"),
    ("Details", "Detalhes"),
    ("Disable", "Desativar"),
    ("Disabled", "Desativado"),
    ("Display", "Exibição"),
    ("Domain", "Domínio"),
    ("Domains", "Domínios"),
    ("Edit", "Editar"),
    ("Email", "E-mail"),
    ("Enable", "Ativar"),
    ("Enabled", "Ativado"),
    ("Error", "Erro"),
    ("Errors", "Erros"),
    ("Export", "Exportar"),
    ("File", "Arquivo"),
    ("Files", "Arquivos"),
    ("Filter", "Filtro"),
    ("General", "Geral"),
    ("Group", "Grupo"),
    ("Groups", "Grupos"),
    ("History", "Histórico"),
    ("Host", "Host"),
    ("Hostname", "Nome do host"),
    ("Import", "Importar"),
    ("Language", "Idioma"),
    ("Last", "Último"),
    ("List", "Lista"),
    ("Loading", "Carregando"),
    ("Login", "Login"),
    ("Logout", "Sair"),
    ("Mail", "E-mail"),
    ("Mailbox", "Caixa postal"),
    ("Manage", "Gerenciar"),
    ("Management", "Gerenciamento"),
    ("Message", "Mensagem"),
    ("Messages", "Mensagens"),
    ("Name", "Nome"),
    ("New", "Novo"),
    ("Next", "Próximo"),
    ("Notification", "Notificação"),
    ("Notifications", "Notificações"),
    ("Operation", "Operação"),
    ("Operations", "Operações"),
    ("Password", "Senha"),
    ("Permission", "Permissão"),
    ("Permissions", "Permissões"),
    ("Policy", "Política"),
    ("Preferences", "Preferências"),
    ("Privacy", "Privacidade"),
    ("Quota", "Cota"),
    ("Remove", "Remover"),
    ("Reset", "Redefinir"),
    ("Resource", "Recurso"),
    ("Resources", "Recursos"),
    ("Restore", "Restaurar"),
    ("Retry", "Tentar novamente"),
    ("Running", "Em execução"),
    ("Save", "Salvar"),
    ("Search", "Pesquisar"),
    ("Server", "Servidor"),
    ("Servers", "Servidores"),
    ("Service", "Serviço"),
    ("Services", "Serviços"),
    ("Setting", "Configuração"),
    ("Settings", "Configurações"),
    ("Status", "Status"),
    ("Storage", "Armazenamento"),
    ("Successful", "Bem-sucedido"),
    ("Successfully", "com sucesso"),
    ("Time", "Hora"),
    ("Timezone", "Fuso horário"),
    ("Type", "Tipo"),
    ("Update", "Atualizar"),
    ("Upload", "Enviar"),
    ("User", "Usuário"),
    ("Users", "Usuários"),
    ("View", "Visualizar"),
    ("Volume", "Volume"),
    ("Volumes", "Volumes"),
    ("Warning", "Aviso"),
]


REGEX_REPLACEMENTS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"^Create (.+)$", re.I), r"Criar \1"),
    (re.compile(r"^Edit (.+)$", re.I), r"Editar \1"),
    (re.compile(r"^Delete (.+)$", re.I), r"Excluir \1"),
    (re.compile(r"^Remove (.+)$", re.I), r"Remover \1"),
    (re.compile(r"^Enable (.+)$", re.I), r"Ativar \1"),
    (re.compile(r"^Disable (.+)$", re.I), r"Desativar \1"),
    (re.compile(r"^Search (.+)$", re.I), r"Pesquisar \1"),
    (re.compile(r"^(.+) successfully$", re.I), r"\1 com sucesso"),
    (re.compile(r"^Are you sure you want to (.+)\?$", re.I), r"Tem certeza de que deseja \1?"),
]


T_CALL_RE = re.compile(
    r"\bt\(\s*(['\"])(?P<key>[^'\"]+)\1\s*,\s*(['\"])(?P<text>(?:\\.|(?!\3).)*)\3",
    re.S,
)
TRANS_RE = re.compile(
    r"<Trans[^>]+i18nKey=(['\"])(?P<key>[^'\"]+)\1[^>]+defaults=(['\"])(?P<text>(?:\\.|(?!\3).)*)\3",
    re.S,
)


def decode_js_string(value: str, quote: str = '"') -> str:
    try:
        return ast.literal_eval(quote + value + quote)
    except Exception:
        return value.replace("\\n", "\n").replace("\\'", "'").replace('\\"', '"')


def flatten_json(value: object, prefix: str = "") -> dict[str, str]:
    result: dict[str, str] = {}
    if isinstance(value, dict):
        for key, child in value.items():
            child_prefix = f"{prefix}.{key}" if prefix else str(key)
            result.update(flatten_json(child, child_prefix))
    elif isinstance(value, str):
        result[prefix] = value
    return result


def extract_sources(source_root: Path) -> dict[str, str]:
    entries: dict[str, str] = {}
    roots = [source_root / "apps", source_root / "packages"]
    for root in roots:
        if not root.exists():
            continue
        for path in root.rglob("*"):
            if path.suffix not in {".ts", ".tsx", ".js", ".jsx"}:
                continue
            text = path.read_text(encoding="utf-8", errors="ignore")
            for match in T_CALL_RE.finditer(text):
                key = match.group("key")
                fallback = decode_js_string(match.group("text"), match.group(3))
                entries.setdefault(key, fallback)
            for match in TRANS_RE.finditer(text):
                key = match.group("key")
                fallback = decode_js_string(match.group("text"), match.group(3))
                entries.setdefault(key, fallback)
    return entries


def translate_by_words(text: str) -> str:
    translated = text
    for pattern, replacement in REGEX_REPLACEMENTS:
        translated = pattern.sub(replacement, translated)
    for english, portuguese in WORD_TRANSLATIONS:
        translated = re.sub(rf"\b{re.escape(english)}\b", portuguese, translated)
    translated = translated.replace(" of ", " de ")
    translated = translated.replace(" for ", " para ")
    translated = translated.replace(" with ", " com ")
    translated = translated.replace(" from ", " de ")
    translated = translated.replace(" to ", " para ")
    translated = translated.replace(" and ", " e ")
    translated = translated.replace(" or ", " ou ")
    translated = translated.replace(" the ", " ")
    translated = translated.replace(" this ", " este ")
    translated = translated.replace(" selected ", " selecionado ")
    translated = re.sub(r"\s+", " ", translated).strip()
    return translated


def translate(key: str, fallback: str, legacy_pt: dict[str, str]) -> str:
    if key in CURATED_TRANSLATIONS:
        return CURATED_TRANSLATIONS[key]
    if key in KEY_TRANSLATIONS:
        return KEY_TRANSLATIONS[key]
    if key in legacy_pt and legacy_pt[key].strip():
        return legacy_pt[key]
    if fallback in EXACT_TRANSLATIONS:
        return EXACT_TRANSLATIONS[fallback]
    if not fallback.strip():
        return fallback
    value = translate_by_words(fallback)
    if fallback.isupper() and len(fallback) > 2:
        value = value.upper()
    return value


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", default="../../../official-sources/carbonio-admin-console-ui")
    parser.add_argument("--legacy-pt", default="../../../official-sources/carbonio-admin-ui/translations/pt.json")
    parser.add_argument("--output", default="../translations/pt.json")
    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent
    source_root = (script_dir / args.source).resolve()
    legacy_path = (script_dir / args.legacy_pt).resolve()
    output_path = (script_dir / args.output).resolve()

    extracted = extract_sources(source_root)
    legacy_pt: dict[str, str] = {}
    if legacy_path.exists():
        legacy_pt = flatten_json(json.loads(legacy_path.read_text(encoding="utf-8")))

    result: dict[str, str] = {}
    for key, value in legacy_pt.items():
        if value.strip():
            result[key] = value

    for key, fallback in sorted(extracted.items()):
        result[key] = translate(key, fallback, legacy_pt)

    result.update(CURATED_TRANSLATIONS)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    untranslated = sum(1 for key, fallback in extracted.items() if result.get(key) == fallback and fallback.strip())
    print(
        json.dumps(
            {
                "source": str(source_root),
                "keys_extracted": len(extracted),
                "keys_written": len(result),
                "untranslated_exact_fallbacks": untranslated,
                "output": str(output_path),
            },
            ensure_ascii=False,
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
